server:
    port: 8001
    servlet.context-path: /chinabank
    
mybatis:
  typeAliasesPackage: com.luochaoqun.tx.chinabank.entity
  mapperLocations: classpath:mapper/*.xml

spring:

  datasource:
    url: jdbc:mysql://47.94.170.165:3306/china_bank?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull
    username: luochaoqun
    password: Luochaoqun123!
    driver-class-name: com.mysql.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    #初始化大小最小最大
    #initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #测试连接是否有效的sql
    validationQuery: select 'x'
    #建议配置为true，不影响性能，并且保证安全性
    #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效
    testOnReturn: false
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxPoolPreparedStatementPerConnectionSize: 20
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有:
    #监控统计用的filter:stat
    #日志用的filter:log4j
    #防御sql注入的filter:wall
    filters: stat,log4j,wall
