server:
  port: 8000

eureka:
  server:
    #自我保护模式关闭，默认开启
    enableSelfPreservation: false
  client:
    healcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: pro
    hostname: localhost
spring:
  application:
    name: eurka-server